export const GET_PRODUCTS_REQ = "GET_PRODUCTS_REQ"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE"

export const GET_CLICKED_PRODUCTS_REQ = "GET_CLICKED_PRODUCTS_REQ"
export const GET_CLICKED_PRODUCTS_SUCCESS = "GET_CLICKED_PRODUCTS_SUCCESS"
export const GET_CLICKED_PRODUCTS_FAILURE = "GET_CLICKED_PRODUCTS_FAILURE"
export const SORT_PRODUCTS = "SORT_PRODUCTS"
export const GET_CLICKED_SINGLE_PRODUCT = "GET_CLICKED_SINGLE_PRODUCT"